"""add users table and document timing columns

Revision ID: 7a3d7d13fc74
Revises: 39a39f45120f
Create Date: 2026-07-27 16:53:38.022729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3d7d13fc74'
down_revision: Union[str, None] = '39a39f45120f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('documents', sa.Column('parsing_started_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('parsing_completed_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('extraction_started_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('extraction_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extraction_completed_at')
    op.drop_column('documents', 'extraction_started_at')
    op.drop_column('documents', 'parsing_completed_at')
    op.drop_column('documents', 'parsing_started_at')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
