"""corrections corrected_value to text

Revision ID: e0612b5a427a
Revises: 0e4ecb9cb7b5
Create Date: 2026-07-27 10:57:38.772918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0612b5a427a'
down_revision: Union[str, None] = '0e4ecb9cb7b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corrections', 'corrected_value',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corrections', 'corrected_value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
    # ### end Alembic commands ###
